### ISSUE TITLE
Ошибка при добавлении документа

### ISSUE THREAD

**Issue by stas12312** [stas12312/my-tickets-bot#28]
TypeError: Ticket.__init__() missing 1 required positional argument: 'event_name'
Traceback (most recent call last):
  File "C:\Users\sv.rush\AppData\Local\pypoetry\Cache\virtualenvs\my-ticket-bot-eICA7wGW-py3.11\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 293, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sv.rush\AppData\Local\pypoetry\Cache\virtualenvs\my-ticket-bot-eICA7wGW-py3.11\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 142, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sv.rush\AppData\Local\pypoetry\Cache\virtualenvs\my-ticket-bot-eICA7wGW-py3.11\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sv.rush\AppData\Local\pypoetry\Cache\virtualenvs\my-ticket-bot-eICA7wGW-py3.11\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 23, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sv.rush\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "C:\Users\sv.rush\AppData\Local\pypoetry\Cache\virtualenvs\my-ticket-bot-eICA7wGW-py3.11\Lib\site-packages\aiogram\fsm\storage\memory.py", line 52, in lock
    yield
  File "C:\Users\sv.rush\AppData\Local\pypoetry\Cache\virtualenvs\my-ticket-bot-eICA7wGW-py3.11\Lib\site-packages\aiogram\fsm\middleware.py", line 34, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\my-ticket-bot\my_tickets_bot\src\bot\middlewares\db_middleware.py", line 38, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sv.rush\AppData\Local\pypoetry\Cache\virtualenvs\my-ticket-bot-eICA7wGW-py3.11\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 111, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sv.rush\AppData\Local\pypoetry\Cache\virtualenvs\my-ticket-bot-eICA7wGW-py3.11\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\sv.rush\AppData\Local\pypoetry\Cache\virtualenvs\my-ticket-bot-eICA7wGW-py3.11\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 260, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sv.rush\AppData\Local\pypoetry\Cache\virtualenvs\my-ticket-bot-eICA7wGW-py3.11\Lib\site-packages\aiogram\dispatcher\router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sv.rush\AppData\Local\pypoetry\Cache\virtualenvs\my-ticket-bot-eICA7wGW-py3.11\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sv.rush\AppData\Local\pypoetry\Cache\virtualenvs\my-ticket-bot-eICA7wGW-py3.11\Lib\site-packages\aiogram\dispatcher\router.py", line 131, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sv.rush\AppData\Local\pypoetry\Cache\virtualenvs\my-ticket-bot-eICA7wGW-py3.11\Lib\site-packages\aiogram\dispatcher\router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sv.rush\AppData\Local\pypoetry\Cache\virtualenvs\my-ticket-bot-eICA7wGW-py3.11\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sv.rush\AppData\Local\pypoetry\Cache\virtualenvs\my-ticket-bot-eICA7wGW-py3.11\Lib\site-packages\aiogram\dispatcher\router.py", line 131, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sv.rush\AppData\Local\pypoetry\Cache\virtualenvs\my-ticket-bot-eICA7wGW-py3.11\Lib\site-packages\aiogram\dispatcher\router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sv.rush\AppData\Local\pypoetry\Cache\virtualenvs\my-ticket-bot-eICA7wGW-py3.11\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sv.rush\AppData\Local\pypoetry\Cache\virtualenvs\my-ticket-bot-eICA7wGW-py3.11\Lib\site-packages\aiogram\dispatcher\router.py", line 124, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sv.rush\AppData\Local\pypoetry\Cache\virtualenvs\my-ticket-bot-eICA7wGW-py3.11\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 111, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sv.rush\AppData\Local\pypoetry\Cache\virtualenvs\my-ticket-bot-eICA7wGW-py3.11\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "D:\Projects\my-ticket-bot\my_tickets_bot\src\bot\handlers\tickets.py", line 125, in processing_file
    await repo.ticket.save(
  File "D:\Projects\my-ticket-bot\my_tickets_bot\src\services\repositories\ticket.py", line 33, in save
    return Ticket(
           ^^^^^^^
TypeError: Ticket.__init__() missing 1 required positional argument: 'event_name'

**Comment by stas12312** [comment]
Не повторяется
